# Generated by Django 2.2 on 2021-02-03 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(verbose_name='Descrição da peça')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Finalizada', 'Finalizada')], max_length=20, verbose_name='Status de Finalização')),
                ('logradouro', models.CharField(max_length=254, verbose_name='Endereço/Logradouro com número')),
                ('complemento', models.CharField(max_length=254, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=254, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=9, verbose_name='Cep')),
                ('email', models.EmailField(max_length=254, verbose_name='Email para contato')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=14, verbose_name='Celular')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='app.Cidades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
