# Generated by Django 2.2 on 2021-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_demandas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidades',
            options={'verbose_name': 'Cidades', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='demandas',
            options={'verbose_name': 'Demandas', 'verbose_name_plural': 'Demandas de Peças'},
        ),
        migrations.AlterField(
            model_name='demandas',
            name='celular',
            field=models.CharField(max_length=16, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Finalizada', 'Finalizada')], default='Aberta', max_length=20, verbose_name='Status de Finalização'),
        ),
    ]
